#!/bin/sh

while true
do
    curl -X POST --header "Content-Type:application/json;charset=UTF-8" -i 'http://172.16.185.114:8080/push/sendToAll' --data '最终目的是能够将各个技术点形成知识体系，有了足够的知识积累方能技术深入，对每个技术点的有研究，大致分为基础用法和原理剖析，最终能够将文章组织的有条理'
    curl -X GET -i 'http://172.16.185.114:8080/push/sendByToken?token=5f6497f77b9621dacd564bfba394ea49&message=pushsiginsad'

    #sleep 1
done
